

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./notebooks:/app/notebooks
  tester:
    build: .
    volumes:
      - ./tests:/app/tests
    command: >
      sh -c "uv pip install --system --no-cache-dir '.[test]' && pytest"
